# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161108_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='readed_list',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscribe_list',
            field=models.CharField(max_length=100),
        ),
    ]
